version: '2'

services:
  web:
    image: nginx:latest
    container_name: "nginx-owasp"
    ports:
      - 9906:80
    env_file: .env
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /var/log/nginx-docker:/var/log/nginx
    links:
      - php
    volumes_from:
      - app-data

  # php
  php:  
    build: ./php/
    container_name: "php7-fpm-owasp"
    env_file: .env
    # expose:
    #   - 9000
    links:
      - mysql
    volumes_from:
      - app-data

  # mysql
  mysql:
    image: mysql:5.7.21
    volumes_from:
      - mysql-data
    #ports:
    #  - "3306:3306"
    container_name: "mysql-owasp"
    env_file: .env
  
  # wordpress data
  app-data:
    image: php:7.0-fpm
    container_name: "app-data-owasp"
    volumes:
      - ./mutillidae-2.6.67:/var/www/html
    command: "true"
  
  # mysql data
  mysql-data:
    image: mysql:5.7.21
    container_name: "mysql-data-owasp"
    volumes:
      - ./db/mysql:/var/lib/mysql
    command: "true"
  
  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "phpmyadmin-owasp"
    ports:
      - 9907:80
    links:
      - mysql
    environment:
      PMA_HOST: mysql